repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.6.7'
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format