repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.6.7'
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the linter again, this time failing on any remaining errors.
      - id: ruff
        args: [ --exit-non-zero-on-fix ]
      # Run the formatter.
      - id: ruff-format